version: '3'
services:
  user-api:
    build: user-api/
    ports:
      - 9999:8080

#    volumes:
#      - ./user-api/:/var/www

  banking-core:
    build: banking-core/
    ports:
      - 9000:9000

#    volumes:
#      - ./banking-core/:/var/www
